language: node_js
node_js:
  - "v11.10.1"
cache:
  directories:
  - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $adw
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: dev